In [52]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import getpass  # To get the password without showing the input
password = getpass.getpass()

# Note that when you use _SQLAlchemy_ and establish the connection, you do not even need to be logged in Sequel Pro or MySQL Workbench.

 ········

In [53]:
#Establish a connection between Python and the Sakila database.
sd = "sakila"
connection_string = 'mysql+pymysql://root:' + password + '@localhost/'+sd
engine = create_engine(connection_string)
engine

Engine(mysql+pymysql://root:***@localhost/sakila)

In [54]:
from sqlalchemy import text

with engine.connect() as connection:
    query = text('SELECT * FROM rental')
    result = connection.execute(query)

result

#2. Write a Python function called `rentals_month` that retrieves rental data for a given month and year (passed as parameters) from the Sakila database as a Pandas DataFrame. The function should take in three parameters:

	- `engine`: an object representing the database connection engine to be used to establish a connection to the Sakila database.
	- `month`: an integer representing the month for which rental data is to be retrieved.
	- `year`: an integer representing the year for which rental data is to be retrieved.

	The function should execute a SQL query to retrieve the rental data for the specified month and year from the rental table in the Sakila database, and return it as a pandas DataFrame.

In [56]:
def rentals_month(engine, month, year):
    with engine.connect() as connection:
        txt = f'''SELECT *, month(rental_date) as month, year(rental_date) as year 
                 FROM rental
                 WHERE month(rental_date) = {month} AND year(rental_date) = {year};'''
        query = text(txt)
        result = connection.execute(query)
        return pd.DataFrame(result.all())

In [57]:
rentals_month(engine, 5, 2005)

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update,month,year
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53,5,2005
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53,5,2005
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53,5,2005
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53,5,2005
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53,5,2005
...,...,...,...,...,...,...,...,...,...
1151,1153,2005-05-31 21:36:44,2725,506,2005-06-10 01:26:44,2,2006-02-15 21:30:53,5,2005
1152,1154,2005-05-31 21:42:09,2732,59,2005-06-08 16:40:09,1,2006-02-15 21:30:53,5,2005
1153,1155,2005-05-31 22:17:11,2048,251,2005-06-04 20:27:11,2,2006-02-15 21:30:53,5,2005
1154,1156,2005-05-31 22:37:34,460,106,2005-06-01 23:02:34,2,2006-02-15 21:30:53,5,2005
1155,1157,2005-05-31 22:47:45,1449,61,2005-06-02 18:01:45,1,2006-02-15 21:30:53,5,2005

In [103]:
def rentals_month(engine, month, year):
      with engine.connect() as connection:
        txt = f'''SELECT *, date_format(return_date, "%m") as month, date_format(return_date, "%Y") as year 
                 FROM rental
                 WHERE date_format(return_date, "%m") = {month} AND date_format(return_date, "%Y") = {year};'''
        query = text(txt)
        result = connection.execute(query)
        return pd.DataFrame(result.all())

In [105]:
rentals_df = rentals_month(engine, 5, 2005)
rentals_df

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update,month,year
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53,05,2005
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53,05,2005
2,6,2005-05-24 23:08:07,2792,549,2005-05-27 01:32:07,1,2006-02-15 21:30:53,05,2005
3,7,2005-05-24 23:11:53,3995,269,2005-05-29 20:34:53,2,2006-02-15 21:30:53,05,2005
4,8,2005-05-24 23:31:46,2346,239,2005-05-27 23:33:46,2,2006-02-15 21:30:53,05,2005
...,...,...,...,...,...,...,...,...,...
390,965,2005-05-30 19:00:14,3363,502,2005-05-31 17:10:14,2,2006-02-15 21:30:53,05,2005
391,966,2005-05-30 19:00:37,1294,496,2005-05-31 23:51:37,1,2006-02-15 21:30:53,05,2005
392,968,2005-05-30 19:20:03,119,576,2005-05-31 18:17:03,2,2006-02-15 21:30:53,05,2005
393,969,2005-05-30 19:23:48,443,551,2005-05-31 21:14:48,1,2006-02-15 21:30:53,05,2005
394,996,2005-05-31 00:06:20,2075,331,2005-05-31 21:29:20,2,2006-02-15 21:30:53,05,2005

3. Develop a Python function called `rental_count_month` that takes the DataFrame provided by `rentals_month` as input along with the month and year and returns a new DataFrame containing the number of rentals made by each customer_id during the selected month and year. 

	The function should also include the month and year as parameters and use them to name the new column according to the month and year, for example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".


	*Hint: Consider making use of pandas [groupby()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)*

In [79]:
#def rental_count_month(rentals_month, month, year):
    #with engine.connect() as connection:
        #rental_counts = rentals_df.groupby("customer_id")["rental_id"].count().reset_index()
        #rental_counts.rename(columns={"rental_id": f"rentals_{month}_{year}"}, inplace=True)
    #return rental_counts
#rental_counts_df = rental_count_month(rentals_df, month, year)
#rental_counts_df

NameError: name 'month' is not defined

In [133]:
def rental_count_month(df, month, year):
    df = df.groupby("customer_id").agg("count")
    df = df.rename(columns ={"rental_date":f"rentals_{month}_{year}"})
    df = df.drop(columns = ["rental_id", "inventory_id", "staff_id", "last_update", "return_date"])
    return df

In [167]:
df_rcm_2005 = rental_count_month(rentals_df, 5, 2005)

In [169]:
df_rcm_2006 = rental_count_month(rentals_df, 2, 2006)

4. Create a Python function called `compare_rentals` that takes two DataFrames as input containing the number of rentals made by each customer in different months and years. 
The function should return a combined DataFrame with a new 'difference' column, which is the difference between the number of rentals in the two months.

In [187]:
def compare_rentals(df1, df2):
    df = pd.merge(df1, df2, on = "customer_id")
    #df['difference'] = df[df.columns[0]]-df[df.columns[1]]
    df['difference'] = df.iloc[:,0] - df.iloc[:,1]
    return df

In [193]:
#df1 = df_rcm(rentals_df(engine, 5, 2005), 5, 2005)
#df2 = df_rcm(rentals_df(engine, 2, 2006), 2, 2006)

df1 = df_rcm_2005
df2 = df_rcm_2006 
compare_rentals(df1, df2)

,rentals_5_2005,month_x,year_x,rentals_2_2006,month_y,year_y,difference
customer_id,,,,,,,
2,1,1,1,1,1,1,0
5,1,1,1,1,1,1,0
6,2,2,2,2,2,2,0
7,1,1,1,1,1,1,0
14,1,1,1,1,1,1,0
...,...,...,...,...,...,...,...
587,2,2,2,2,2,2,0
589,2,2,2,2,2,2,0
594,1,1,1,1,1,1,0
596,2,2,2,2,2,2,0
597,1,1,1,1,1,1,0

In [ ]:
def compare_rentals(df1, df2, col1, col2):\n",
# Merge the two DataFrames on the 'customer_id' column.\n",
# Use an outer join to include all customers from both DataFrames.\n",
# Add suffixes to distinguish columns from the first and second DataFrame.\n",
combined_df = pd.merge(df1, df2, on='customer_id', how='outer', suffixes=('_first', '_second'))\n",
\n",
# Replace any NaN values with 0 in the merged DataFrame\n",
combined_df.fillna(0, inplace=True)\n",
\n",
# Calculate the difference between the specified columns from the two original DataFrames\n",
# and store it in a new column called 'diferencia'\n",
combined_df['diferencia'] = combined_df[f'{col1}'] - combined_df[f'{col2}']\n",
    "    \n",
    "    # Return the DataFrame with the merged data and calculated differences\n",
    "    return combined_df"